version: '0.6.7-alpha{build}'
image: Visual Studio 2017
configuration:
- Release
platform: Any CPU
init:
- ps: $Env:LABEL = "alpha" + $Env:APPVEYOR_BUILD_NUMBER
before_build:
- dotnet restore "src\Microphone.sln"
build_script:
- dotnet build "src\Microphone.sln" -c %CONFIGURATION% --version-suffix %LABEL%
after_build:
- dotnet pack "src\Microphone.sln" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
artifacts:
- path: \**\artifacts\**\*.nupkg
